server:
  port: 8085

spring:
  application:
    name: payment-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db?currentSchema=payment_schema
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: payment_schema
        hbm2ddl.create_namespaces: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: java.util.HashMap
        spring.json.use.type.headers: false

app:
  kafka:
    topic:
      order-created: order-events
      inventory-reserved: inventory-reserved-events
      payment-success: payment-events

eureka:
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: localhost:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  info:
    env:
      enabled: true

info:
  app:
    name: payment-service
    description: Microservice for payment-service
    version: 1.0.0
